# Generated by Django 2.1 on 2018-10-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20181012_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='repely_to',
            new_name='reply_to',
        ),
    ]
